### ISSUE TITLE
Opcode Wishlist

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/thelonious#42]
Keep all opcode requests and discussion here

- [ ] EXTLOAD : inspect the storage of other contracts (https://github.com/eris-ltd/thelonious/issues/38)
- [ ] modified SHA3: take arg off the stack (https://github.com/eris-ltd/thelonious/issues/39)
- [ ] MIMIC: codecopy from another contract (https://github.com/eris-ltd/thelonious/issues/34)
- [ ] NOVA: create new contract with same storage, different code (https://github.com/eris-ltd/thelonious/issues/33)
- [ ] REVERT: revert all changes in a state transition (https://github.com/eris-ltd/thelonious/issues/26)

**Comment by compleatang** [comment]
these appear all finished... mind if we close and folks can open issues if they need new opcodes?

**Comment by ebuchman** [comment]
i don't think any of these opcodes actually got done. id like to leave this open but take the milestone off

**Comment by compleatang** [comment]
sounds good.
